apiVersion: monitoring.coreos.com/v1
kind: Alertmanager
metadata:
  name: {{ .ApplicationMonitoringName }}
  namespace: {{ .Namespace }}
  labels:
    alertmanager: {{ .ApplicationMonitoringName }}
spec:
  baseImage: {{ .ImageAlertManager }}
  tag: "{{ .ImageTagAlertManager }}"
  externalUrl: https://{{ index .ExtraParams "alertmanagerHost" }}
  listenLocal: true
  serviceAccountName: {{ .AlertManagerServiceAccountName }}
  replicas: {{ .Replicas }}
  containers:
    - args:
        - '-provider=openshift'
        - '-https-address=:9091'
        - '-http-address='
        - '-email-domain=*'
        - '-upstream=http://localhost:9093'
        - '-openshift-sar={"resource": "namespaces", "verb": "get"}'
        - '-openshift-delegate-urls={"/": {"resource": "namespaces", "verb": "get"}}'
        - '-tls-cert=/etc/tls/private/tls.crt'
        - '-tls-key=/etc/tls/private/tls.key'
        - '-client-secret-file=/var/run/secrets/kubernetes.io/serviceaccount/token'
        - '-cookie-secret-file=/etc/proxy/secrets/session_secret'
        - "-openshift-service-account={{ .AlertManagerServiceAccountName }}"
        - '-openshift-ca=/etc/pki/tls/cert.pem'
        - '-openshift-ca=/var/run/secrets/kubernetes.io/serviceaccount/ca.crt'
        - '-skip-auth-regex=^/metrics'
      env:
        - name: HTTP_PROXY
        - name: HTTPS_PROXY
        - name: NO_PROXY
      image: '{{ .ImageOAuthProxy }}:{{ .ImageTagOAuthProxy }}'
      name: alertmanager-proxy
      ports:
        - containerPort: 9091
          name: oproxy
      resources: {}
      volumeMounts:
        - mountPath: /etc/tls/private
          name: secret-alertmanager-k8s-tls
        - mountPath: /etc/proxy/secrets
          name: secret-alertmanager-k8s-proxy
  secrets:
    - alertmanager-k8s-tls
    - alertmanager-k8s-proxy
{{- if .PriorityClassName }}
  priorityClassName: {{.PriorityClassName}}
{{- end }}
{{- if .Affinity }}
  affinity:
{{ .Affinity | indent 4 }}
{{- end }}
