apiVersion: monitoring.coreos.com/v1
kind: Prometheus
metadata:
  name: {{ .ApplicationMonitoringName }}
  namespace: {{ .Namespace }}
  labels:
    prometheus: {{ .ApplicationMonitoringName }}
spec:
  baseImage: {{ .ImagePrometheus }}
  tag: "{{ .ImageTagPrometheus }}"
  replicas: {{ .Replicas }}
  containers:
    - name: blackbox-exporter
      volumeMounts:
        - name: configmap-{{ .BlackboxExporterConfigmapName }}
          mountPath: /etc/blackbox-config
        - mountPath: /etc/tls/private
          name: secret-prometheus-k8s-tls
      image: {{ .ImageBlackboxExporter }}:{{ .ImageTagBlackboxExporter }}
      args:
        - '--config.file=/etc/blackbox-config/blackbox.yml'
      ports:
        - containerPort: 9115
          name: blackbox
    - args:
        - '-provider=openshift'
        - '-https-address=:9091'
        - '-http-address='
        - '-email-domain=*'
        - '-upstream=http://localhost:9090'
        - "-openshift-service-account={{ .PrometheusServiceAccountName }}"
        - '-openshift-sar={"resource": "namespaces", "verb": "get"}'
        - '-openshift-delegate-urls={"/": {"resource": "namespaces", "verb":"get"}}'
        - '-tls-cert=/etc/tls/private/tls.crt'
        - '-tls-key=/etc/tls/private/tls.key'
        - '-client-secret-file=/var/run/secrets/kubernetes.io/serviceaccount/token'
        - '-cookie-secret-file=/etc/proxy/secrets/session_secret'
        - '-openshift-ca=/etc/pki/tls/cert.pem'
        - '-openshift-ca=/var/run/secrets/kubernetes.io/serviceaccount/ca.crt'
        - '-skip-auth-regex=^/metrics'
      image: '{{ .ImageOAuthProxy }}:{{ .ImageTagOAuthProxy }}'
      name: prometheus-proxy
      ports:
        - containerPort: 9091
          name: oproxy
      resources: {}
      volumeMounts:
        - mountPath: /etc/tls/private
          name: secret-prometheus-k8s-tls
        - mountPath: /etc/proxy/secrets
          name: secret-prometheus-k8s-proxy
  externalUrl: https://{{ index .ExtraParams "prometheusHost" }}
  alerting:
    alertmanagers:
      - name: {{ .AlertManagerServiceName }}
        namespace: {{ .Namespace }}
        port: web
        scheme: https
        bearerTokenFile: /var/run/secrets/kubernetes.io/serviceaccount/token
        tlsConfig:
          caFile: /var/run/secrets/kubernetes.io/serviceaccount/service-ca.crt
          serverName: "{{ .AlertManagerServiceName }}.{{ .Namespace }}.svc"
  resources:
    requests:
      memory: 400Mi
  retention: {{ .PrometheusRetention }}
  secrets:
    - prometheus-k8s-tls
    - prometheus-k8s-proxy
  configMaps:
    - {{ .BlackboxExporterConfigmapName }}
  serviceAccountName: {{ .PrometheusServiceAccountName }}
  serviceMonitorNamespaceSelector:
    matchExpressions:
      - { key: "monitoring-key", operator: In, values: [{{ .MonitoringKey }}] }
  serviceMonitorSelector:
    any: true
  ruleSelector:
    any: true
  ruleNamespaceSelector:
    matchExpressions:
      - { key: "monitoring-key", operator: In, values: [{{ .MonitoringKey }}] }
  podMonitorNamespaceSelector:
    matchExpressions:
      - { key: "monitoring-key", operator: In, values: [{{ .MonitoringKey }}] }
  podMonitorSelector:
    any: true
  additionalScrapeConfigs:
    name: {{ .ScrapeConfigSecretName }}
    key: integreatly.yaml
{{- if .PriorityClassName}}
  priorityClassName: {{.PriorityClassName}}
{{- end}}
{{- if .PrometheusStorageRequest}}
  storage:
    volumeClaimTemplate:
      spec:
        resources:
          requests:
            storage: {{.PrometheusStorageRequest}}
{{- end}}
{{- if .Affinity }}
  affinity:
{{ .Affinity | indent 4 }}
{{- end }}
